<a href="https://colab.research.google.com/github/Sid-istic/GNSS_Predictions/blob/main/Data_Cleaining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Installing Dependencies**

In [ ]:
!pip install pandas numpy scikit-learn tensorflow matplotlib

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.76.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.18.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.1.4)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.5)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from google.colab import files
import joblib

**Data Loading**

In [ ]:
train_files = [
    "DATA_MEO_Train.csv",
    "DATA_MEO_Train2.csv"
]

test_files = [
    "DATA_MEO_Test.csv",
    "DATA_MEO_Test2.csv"
]

In [ ]:
train_df_1 = pd.read_csv(train_files[0])
train_df_2 = pd.read_csv(train_files[1])

train_df_1.columns = train_df_1.columns.str.replace(" ", "")
train_df_2.columns = train_df_2.columns.str.replace(" ", "")

print("Train shape:", train_df_1.shape)
print("Test shape:", train_df_2.shape)
print("Columns:", train_df_1.columns.tolist())
print("Columns:", train_df_2.columns.tolist())

Train shape: (90, 5)
Test shape: (244, 5)
Columns: ['utc_time', 'x_error(m)', 'y_error(m)', 'z_error(m)', 'satclockerror(m)']
Columns: ['utc_time', 'x_error(m)', 'y_error(m)', 'z_error(m)', 'satclockerror(m)']

In [ ]:
train_df = pd.concat([train_df_1, train_df_2], axis=0)
print("Train shape:", train_df.shape)

Train shape: (334, 5)

In [ ]:
train_df.head()
train_df.tail()

           utc_time  x_error(m)  y_error(m)  z_error(m)  satclockerror(m)
239  9/9/2025 11:01   -0.055010   -0.078045   -0.001801         -0.023807
240  9/9/2025 11:11   -0.065204   -0.069992    0.010225         -0.006356
241  9/9/2025 11:21   -0.092394   -0.083031   -0.013661         -0.006356
242  9/9/2025 11:31   -0.038481   -0.027933    0.020780         -0.006356
243  9/9/2025 11:41   -0.004811   -0.092135    0.052409         -0.021234

In [ ]:
test_df_1 = pd.read_csv(test_files[0])
test_df_2 = pd.read_csv(test_files[1])

test_df_1.columns = test_df_1.columns.str.replace(" ", "")
test_df_2.columns = test_df_2.columns.str.replace(" ", "")

print("Train shape:", test_df_1.shape)
print("Test shape:", test_df_2.shape)

Train shape: (11, 5)
Test shape: (30, 5)

In [ ]:
test_df = pd.concat([test_df_1, test_df_2], axis=0)
print("Test shape:", test_df.shape)

Test shape: (41, 5)

In [ ]:
test_df.head()

         utc_time  x_error(m)  y_error(m)  z_error(m)  satclockerror(m)
0  9/8/2025 15:00   -0.595482    0.319356    0.794950         -0.072124
1  9/8/2025 16:00   -0.563411   -0.044653    0.774602         -0.185823
2  9/8/2025 17:00   -0.603752   -0.271075    0.676786          0.047174
3  9/8/2025 18:00   -0.640059   -0.463216    0.329910          0.007417
4  9/8/2025 19:00   -0.845061   -0.542392    0.099746          0.025050

**Data Cleaning**

In [ ]:
train_df["utc_time"] = pd.to_datetime(train_df["utc_time"])
test_df["utc_time"]  = pd.to_datetime(test_df["utc_time"])

train_df = train_df.sort_values("utc_time").reset_index(drop=True)
test_df  = test_df.sort_values("utc_time").reset_index(drop=True)

In [ ]:
train_df.head()

             utc_time  x_error(m)  y_error(m)  z_error(m)  satclockerror(m)
0 2025-09-01 14:00:00   -0.765883    0.671544    0.434251         -0.183989
1 2025-09-01 14:00:00   -0.765883    0.671544    0.434251         -0.183989
2 2025-09-01 15:00:00   -0.568186    0.392191    0.637844         -0.159422
3 2025-09-01 15:00:00   -0.568186    0.392191    0.637844         -0.159422
4 2025-09-01 16:00:00   -0.535862    0.174319    0.723323          0.035761

In [ ]:
train_df.isna().sum()

utc_time            0
x_error(m)          0
y_error(m)          0
z_error(m)          0
satclockerror(m)    0
dtype: int64

In [ ]:
FEATURE_COLS = ["x_error(m)", "y_error(m)", "z_error(m)", "satclockerror(m)"]
TARGET_COL = "satclockerror(m)"

scaler = MinMaxScaler()

train_df[FEATURE_COLS] = scaler.fit_transform(train_df[FEATURE_COLS])
test_df[FEATURE_COLS]  = scaler.transform(test_df[FEATURE_COLS])

In [ ]:
train_df.head()

             utc_time  x_error(m)  y_error(m)  z_error(m)  satclockerror(m)
0 2025-09-01 14:00:00    0.615697    0.859888    0.725431          0.237027
1 2025-09-01 14:00:00    0.615697    0.859888    0.725431          0.237027
2 2025-09-01 15:00:00    0.696596    0.715996    0.838901          0.247677
3 2025-09-01 15:00:00    0.696596    0.715996    0.838901          0.247677
4 2025-09-01 16:00:00    0.709823    0.603773    0.886542          0.332290

**Exporting the Datasets**

In [ ]:
train_df.to_csv("train_df.csv", index=False)
files.download("train_df.csv")
test_df.to_csv("test_df.csv", index=False)
files.download("test_df.csv")

**Exporting Scaler Model**

In [ ]:
joblib.dump(scaler, "scaler_model.pkl")

['scaler_model.pkl']